name: Erik Storm
favicon: null
layout_spectrum: 0.07656554947607219
typography_spectrum: 0.2803315897472203
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.17649441654793918
  lightness: 0.06839971500448883
  saturation: 0.11831962154246867
  rhythmicContrast: 0.2680339196231216
purpose: []
