name: Erik Storm
favicon: null
layout_spectrum: 0.99861
typography_spectrum: 0.20105
title: Ragnarok
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#657781'
    - '#403d39'
    - '#b5b8ab'
    - '#000000'
  brandStrength: 0.8125
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.2680339196231216
purpose: []
